kind: pipeline
name: pywappalyzer

steps:
  - name: pywappalyzer-test
    pull: if-not-exists
    image: python:3.7
    commands:
      - pip install invoke
      - pip install -r requirements.txt
      - inv check
      - inv test